        
                                                  ░░░░░██╗░█████╗░██╗░░░██╗░█████╗░
                                                  ░░░░░██║██╔══██╗██║░░░██║██╔══██╗
                                                  ░░░░░██║███████║╚██╗░██╔╝███████║
                                                  ██╗░░██║██╔══██║░╚████╔╝░██╔══██║
                                                  ╚█████╔╝██║░░██║░░╚██╔╝░░██║░░██║
                                                  ░╚════╝░╚═╝░░╚═╝░░░╚═╝░░░╚═╝░░╚═╝


𝐇𝐨𝐰 𝐭𝐨 𝐀𝐩𝐩𝐫𝐨𝐚𝐜𝐡 𝐭𝐡𝐞 𝐏𝐫𝐨𝐛𝐥𝐞𝐦??

Lets take an Example:-
When we solve math problem first we see the problem and understand the problem , after we think about the problem what process we need to do follow to solve the problem then we execute or solve the problem. 

Same steps are followed in flowchart so steps would be analyze the problem
                                     ______________________________________________________
                                    |                                                      |
   _____________             _______________              _______________             ____________
  | Analyze the |           |   Think of    |            |   Pen Down    |           |  Code the  |
  |   Problem   |---------->|   Solution    |----------->|  The Solution |---------->|  Solution  |
  |_____________|           |_______________|            |_______________|           |____________|

Solving the Problem in Computer actually we need to code But we should not jump to think of solution to code of soluton . Before going to code pen down the solution is most important part. 